### ISSUE TITLE
Add Text Category 

### ISSUE THREAD

**Issue by JuanCorp** [d5555/TagEditor#1]
Hey! 

Great editor, loving it so far. Is it possible to add Text Categories to the possible pipelines? I suppose you can already do it with the NER tags by  selecting the whole sentence and adding a tag to it. But it would be great to do it in a separate module. 

Thanks!

**Comment by d5555** [comment]
I think I could add it. But I'm not sure about how the end result should look.  Could you bring some examples of Training Data with Text Categories ?  Do you need to put a label on each sentence or on the whole doc or paragraph? Should the resulted Training Data include dependencies and pos tags as well .

**Comment by JuanCorp** [comment]
TagEditor works best with whole documents, and use cases for text classification can range from whole documents to sentences. But for this case I was thinking more of sentence classification, or at least the capability to highlight a portion of the text, and add a classification tag to it. From what I've gathered, the spacy text categorization API accepts tuples of (text, category).  Some examples would be (straight from the prodigy examples):

(Improve documentation for service and token urls, documentation)
(Docker for Windows fails to start, instructions) 

Since POS, and NER tags are mostly independent of the underlying document structure, it would be best to include them as is. But for classification, it should be a free text highlight. But that would affect the final DATA structure, maybe include them  at the paragraph level of the JSON, with a list of objects with the keys: text, start_position, end_position, classification.  

What's your suggestion?

**Comment by d5555** [comment]
Thanks for your feedback. Let me see what I can do. Sentence classification won't be difficult to add

**Comment by d5555** [comment]
Text categories option was added.  Read How to use.   Category and Score labels in the editor window act like buttons. To quickly switch the score  true/false without going to TAG SET panel  just click on the label.

**Comment by JuanCorp** [comment]
That was quick, thanks! 

I'll be testing it right now.

**Comment by JuanCorp** [comment]
It's awesome! No need to use a very inefficient tagging page through a local server any more. All my tagging needs in one place.  

Thanks a lot!
