### ISSUE TITLE
Adding spacy model

### ISSUE THREAD

**Issue by jhammelpros** [d5555/TagEditor#2]
Thanks for this very nice tagging tool!
I have some problems adding the large model to the project. As simply copying it into the ./data folder does not seem to work out, could you give a short introduction?

Best,
Johannes

**Comment by jhammelpros** [comment]
Awesome, we really appreciate what you are doing here!
Is a release date already fixed? If not, is there a way to contribute?

**Comment by d5555** [comment]
Other models are not included in this version to make the application compact and portable. Email gitprojects5@gmail.com  if you need extra models or other options for your project.

**Comment by JuanCorp** [comment]
Any chance to add a custom model to the Models list? 

For example, you create training data using TagEditor, create a model for your use case, then use the pipelines of the model to automatically tag text, like the 'en' model does. 

I thought this feature was for this use case, although I don't know what TagEditor does under the hood to specifically auto tag for the en_web_sm_core model.

**Comment by d5555** [comment]
now it can add  -md and -lg models. Just put them into data folder
