### ISSUE TITLE
Sentence Tokenization fails on some sentences, allow for disabling of automatic sentence tokenization!

### ISSUE THREAD

**Issue by laundmo** [d5555/TagEditor#3]
Hey

im currently trying to tag some comments fro mreddit, and the built in sentence tokenization is messing up my data. Ive found that there are several cases where the spacy tokenization fails, one example being `If you haven't played them yet i'd highly recommend you do.` which gets split into 2 lines: `If you haven't played them yet` - `i'd highly recommend you do.`

This is a problem as it messes up my data severely. I would like a option to turn this tokenization off, as ive already done it while extracting the data.

**Comment by d5555** [comment]
I just tried it and the sentence was tokenized properly
![Scr61](https://user-images.githubusercontent.com/40742416/65875493-022cfb00-e34d-11e9-880c-9f7cf5d197f0.png)
Anyway the tokenization depends on Spacy model... by default TagEditor uses the en_core_web_sm
In the full version you can try different models.
You can always manually correct tokenization ,"right click" on the sentence first token and uncheck "sentence start" so it merges with the previous sentence.
