### ISSUE TITLE
Want a feature to edit text after starting annotation

### ISSUE THREAD

**Issue by santhoshsridhar0304** [d5555/TagEditor#3]
First of all,  thanks for the tool. It is working cool and very handy to annotate entities and create the training dataset. Currently, I have a problem with the tool, once we start tagging, I'm not able to change the text of the file loaded. I want this feature because I don't want unwanted text in the dataset after annotating. Will this feature be possible?

**Comment by santhoshsridhar0304** [comment]
I tried this it worked well when inserting. But while deleting, if I select and delete a particular line, the tool is deleting the whole paragraph which I inserted before.

**Comment by santhoshsridhar0304** [comment]
Even it will be fine if **back to text** button remembers the previously annotated entities. I can add the new text there and start annotating the remaining part. The issue is each time, I'm forced to start annotating the entities from the first.

**Comment by d5555** [comment]
Hi santhoshsridhar0304,
yes, you can add a token but not sentence. To add a sentence you need to insert token by token and to set the fist token as a sentence start. But I can probably add new option to the context menu 'Add sentence'. I will work on it. 
**back to text** button restores original text. I don't think I want to change that.

**Comment by santhoshsridhar0304** [comment]
Thank you @d5555 , It will be really helpful if you add that **Add sentence** option. I'm eagerly waiting for the update.

**Comment by d5555** [comment]
I didn't have time to test it extensively yet but you can try already. It can `insert tokens`, they will be tokenized, `insert text` and `delete sentence` .

**Comment by santhoshsridhar0304** [comment]
Thank you @d5555, It's working great.
