### ISSUE TITLE
Not able to open existing project

### ISSUE THREAD

**Issue by santhoshsridhar0304** [d5555/TagEditor#4]
Hi, @d5555, the tool is not working well when I open an old project. It is treating the old one as a new project and not showing my previously annotated entities. If I click **start tagging** button. I'm able to see my old entities annotated. But, **create data** and other options are missing.

![capture](https://user-images.githubusercontent.com/44573572/51680438-c5fc0a80-2007-11e9-8654-107caa9fc36b.PNG)

I'm able to see only **Start Tagging**

**Comment by d5555** [comment]
to Save the project... you do  `File` --> `Save project as `. All the info will be saved to a binary file with the extension  `.data` .  To open it  -  `File` --> `Open project `.

**Comment by santhoshsridhar0304** [comment]
yeah...this is what I'm doing....but the project is treated as a new project. I can only see start tagging button

**Comment by d5555** [comment]
Send me a screenshot please of what you are seeing in tag editor when you are trying to open it.  
You won't be able to see your  old annotated entities  because it is a binary file. You probably saved it as text and then you are trying to open it as a project. You should save it as a project first.

**Comment by santhoshsridhar0304** [comment]
No, I saved it as a project...Not as a text file. If I would have saved as a text file. How would I be able to open as project using **Open Project...**

**Comment by d5555** [comment]
I was not able to reproduce the behavior but I fixed a couple things that could be related to the issue.
