### ISSUE TITLE
TagEditor.exe not working

### ISSUE THREAD

**Issue by sushilr007** [d5555/TagEditor#8]
After unpacking tagdEditor.7z when I run "TagEditor.exe", it is giving an error as "Failed to execute script Editor156_demo".

**Comment by d5555** [comment]
Are you running it on Windows 10 64 bit ? 
I just launched it from archive without unpacking... all worked 
I can not check on other systems at the moment but it works on Windows 10.

**Comment by sushilr007** [comment]
@d5555  I just restarted my laptop and it's working now.
